version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install dev dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install-dev
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test
workflows:
  main:
    jobs:
      - build 
